I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1747, in script
    if saturday1_list[0] == 4 or saturday1_list[0] == 5:
  File "game/script.rpy", line 1747, in <module>
    if saturday1_list[0] == 4 or saturday1_list[0] == 5:
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1747, in script
    if saturday1_list[0] == 4 or saturday1_list[0] == 5:
  File "renpy/ast.py", line 1898, in execute
    if renpy.python.py_eval(condition):
  File "renpy/python.py", line 2276, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2269, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 1747, in <module>
    if saturday1_list[0] == 4 or saturday1_list[0] == 5:
  File "renpy/python.py", line 992, in __getitem__
    rv = list.__getitem__(self, index)
IndexError: list index out of range

Windows-10-10.0.22000
Ren'Py 7.4.11.2266
 
Mon Apr 18 18:53:22 2022
