I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1574, in script call
    call saturday1
  File "game/branc.rpy", line 280, in script call
    call saturday1_morn_pc
  File "game/branc.rpy", line 381, in script call
    call events_run_period
  File "game/dse-event_dispatcher.rpy", line 297, in script call
    call expression _event from call_expression_event_1
  File "game/dse-events.rpy", line 1320, in script
    extned "..."
Exception: Sayer 'extned' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1574, in script call
    call saturday1
  File "game/branc.rpy", line 280, in script call
    call saturday1_morn_pc
  File "game/branc.rpy", line 381, in script call
    call events_run_period
  File "game/dse-event_dispatcher.rpy", line 297, in script call
    call expression _event from call_expression_event_1
  File "game/dse-events.rpy", line 1320, in script
    extned "..."
  File "renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'extned' is not defined.

Windows-10-10.0.22000
Ren'Py 7.4.11.2266
 
Thu Mar 24 18:42:15 2022
