I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1686, in script
    jeogn "그래, 빨리 가서 자."
Exception: Sayer 'jeogn' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1686, in script
    jeogn "그래, 빨리 가서 자."
  File "renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'jeogn' is not defined.

Windows-10-10.0.22000
Ren'Py 7.4.11.2266
 
Mon Apr  4 13:05:15 2022
