I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1296, in script
    show main_ord_ita at [blur2, center]
TypeError: 'RevertableList' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1296, in script
    show main_ord_ita at [blur2, center]
  File "C:\Users\jaejun\Downloads\renpy-7.3.5-sdk/renpy/ast.py", line 1197, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\jaejun\Downloads\renpy-7.3.5-sdk/renpy/ast.py", line 1167, in show_imspec
    atl=atl)
  File "C:\Users\jaejun\Downloads\renpy-7.3.5-sdk/renpy/exports.py", line 754, in show
    img = i(img)
TypeError: 'RevertableList' object is not callable

Windows-10-10.0.18362
Ren'Py 7.4.11.2266
 
Mon Mar 14 09:59:37 2022
